version: "3"
services:
  db:
    image: postgres:9.6.21-alpine
    env_file: .env
    volumes:
      - db:/var/lib/mysql:rw
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    restart: always

  api:
    build:
      context: .
    env_file: .env
    depends_on:
      - db
    expose:
      - ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}

volumes:
  db: